config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :songs
  resources :billboards do
    resources :songs
  end

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  # belongs_to :billboard, optional: true
  # belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :get_artist, only: [:edit, :show]
  
  def index
    @artists = Artist.all
  end

  def show
  end

  def edit
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end    
  end

  def destroy
    Artist.find(params[:id]).destroy
    redirect_to artists_path
  end

  private
  
  def get_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :get_billboard, only: [:edit, :show]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def edit
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def update
    @billboard = Billboard.find(params[:id])
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render :edit
    end    
  end

  def destroy
    Billboard.find(params[:id]).destroy
    redirect_to billboards_path
  end

  private
  
  def get_billboard
    @billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:title, :rank)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :get_song, only: [:edit, :show]
  
  def index
    @songs = Song.all
  end

  def show
  end

  def edit
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end    
  end

  def destroy
    Song.find(params[:id]).destroy
    redirect_to songs_path
  end

  private
  
  def get_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :duration, :genre, :album)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/artists/edit.html.erb
<h1>Editing: <%= @artist.name%></h1>

<hr />

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<% if @artists.any? %>
  <div class='ui grid'>
    <% @artists.each do |artist| %>
      <div class="center aligned four wide column">
        <h3 class='ui card'>
          <%= link_to artist.name, artist_path(artist) %>
        </h3>
      </div>
    <% end %>
  </div>
<% else %>
  <h4> No Artists Listed!</h4>
<% end %>


<div class="ui one column grid">
  <div class="column">
    <div class="three ui buttons">
      <div class='test' class="column"><%= link_to 'Add New Artist', new_artist_path, class: 'ui primary button' %></div>
      <div class='test' class="column"><%= link_to 'All Billboards', billboards_path, class: 'ui primary button' %></div>
      <div class='test' class="column"><%= link_to 'All Songs', songs_path, class: 'ui primary button' %></div>
    </div>
  </div>

app/views/artists/new.html.erb
<h1>Add Artist</h1>
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.submit %>
<% end %>
<%= link_to 'All Artists', artists_path, class: 'btn btn-primary' %>

app/views/artists/show.html.erb
<h1>
  <%= @artist.name %>
</h1>
<br />

<hr />

<div class='action-buttons'>
  <%= link_to 'All Artists', artists_path %>
  <%= link_to 'Edit', edit_artist_path(@artist) %>
  <%= link_to 'Delete', artist_path(@artist), method: :delete, data: {confirm: 'Really Delete?'} %>
</div>

app/views/billboards/edit.html.erb
<h1>Editing: <%= @billboard.title%></h1>

<hr />

<%= form_for @billboard do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1>Music Billboards</h1>
<% if @billboards.any? %>
  <div class='ui grid'>
    <% @billboards.each do |billboard| %>
      <div class="center aligned four wide column">
        <h3 class='ui card'>
          <%= link_to billboard.title, billboard_path(billboard) %>
        </h3>
      </div>
    <% end %>
  </div>
<% else %>
  <h4> No Billboards Listed!</h4>
<% end %>

<div class="ui one column grid">
  <div class="column">
    <div class="three ui buttons">
      <div class='test' class="column"><%= link_to 'Add New Billboard', new_billboard_path, class: 'ui primary button' %></div>
      <div class='test' class="column"><%= link_to 'All Artists', artists_path, class: 'ui primary button' %></div>
      <div class='test' class="column"><%= link_to 'All Songs', songs_path, class: 'ui primary button' %></div>
    </div>
  </div>
  

app/views/billboards/new.html.erb
<h1>Add Billboard</h1>
<%= form_for @billboard do |f| %>
  <div class='ui form'>
    <%= f.label :title, autofocus: true %>
    <%= f.text_field :title, required: true %>
    <br />
  <div class='test'>
    <%= f.submit class: 'ui primary button' %>
  </div>
  </div>
<% end %>
<%= link_to 'All Billboards', billboards_path %>

app/views/billboards/show.html.erb
<h1>
  <%= @billboard.title %>
</h1>
<br />

<hr />

<div class='action-buttons'>
  <%= link_to 'All Posts', billboards_path %>
  <%= link_to 'Edit', edit_billboard_path(@billboard) %>
  <%= link_to 'Delete', billboard_path(@billboard), method: :delete, data: {confirm: 'Really Delete?'} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='ui container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Editing: <%= @song.name%></h1>

<hr />

<%= form_for @song do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :duration %>
  <%= f.text_field :duration, required: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <%= f.label :album %>
  <%= f.text_field :album, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>Songs</h1>
<% if @songs.any? %>
  <div class='ui grid'>
    <% @songs.each do |song| %>
      <div class="center aligned four wide column">
        <h3 class='ui card'>
          <%= link_to song.name, song_path(song) %>
        </h3>
      </div>
    <% end %>
  </div>
<% else %>
  <h4> No Songs Listed!</h4>
<% end %>

<div class="ui one column grid">
  <div class="column">
    <div class="three ui buttons">
      <div class='test' class="column"><%= link_to 'Add New Song', new_song_path, class: 'ui primary button' %></div>
      <div class='test' class="column"><%= link_to 'All Billboards', billboards_path, class: 'ui primary button' %></div>
      <div class='test' class="column"><%= link_to 'All Songs', songs_path, class: 'ui primary button' %></div>
    </div>
  </div>

app/views/songs/new.html.erb
<h1>Add Song</h1>
<%= form_for @song do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :duration %>
  <%= f.text_field :duration, required: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <%= f.label :album %>
  <%= f.text_field :album, required: true %>
  <br />
  <%= f.submit %>
<% end %>
<%= link_to 'All Songs', songs_path, class: 'btn btn-primary' %>

app/views/songs/show.html.erb
<h1>
  <%= @song.name %>
</h1>
<blockquote>
  Duration: <%= @song.duration %>
</blockquote>
<br />
<blockquote>
  Genre: <%= @song.genre %>
</blockquote>
<br />
<blockquote>
  Albumr: <%= @song.album %>
</blockquote>
<br />

<hr />

<div class='action-buttons'>
  <%= link_to 'All Posts', songs_path %>
  <%= link_to 'Edit', edit_song_path(@song) %>
  <%= link_to 'Delete', song_path(@song), method: :delete, data: {confirm: 'Really Delete?'} %>
</div>